---
abstract: 'helps you to make something around computer vision.'
author:
  - 'MASUDA Yuta <yuta.cpan@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cv
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MM_Cygwin: 6.62
  ExtUtils::ParseXS: 2.22
  ExtUtils::PkgConfig: 1.12
  Test::Exception: 0.31
  Test::Number::Delta: 1.03
version: 0.25
