---
abstract: 'helps you to make something around computer vision.'
author:
  - 'MASUDA Yuta <yuta.cpan@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cv
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: 0
  Data::Dumper: 0
  ExtUtils::MM_Cygwin: 6.62
  ExtUtils::ParseXS: 3.07
  File::Basename: 0
  List::Util: 0
  Scalar::Util: 0
  Time::HiRes: 0
version: 0.21
