--- #YAML:1.0
name:               Cv
version:            0.08
abstract:           helps you to make something around computer vision.
author:
    - MASUDA Yuta <yuta.masuda@newdaysys.co.jp>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cwd:                  0
    Data::Dumper:         0
    ExtUtils::PkgConfig:  0
    File::Basename:       0
    List::Util:           0
    Scalar::Util:         0
    Time::HiRes:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
